### ISSUE TITLE
sample_data.csv

### ISSUE THREAD

**Issue by SpaceDustPi** [goodboychan/goodboychan.github.io#76]
Hi,

Where is your sample_data.csv? It was in your 'school budgeting' code, but I cannot find it.

Thanks,
Ben

**Comment by goodboychan** [comment]
Hi,
Mentioned in page, the original data from datacamp is huge. So it cannot be store in my repo. But you can download the alternative one in [kaggle](https://www.kaggle.com/jeromeblanchet/drivendatas-boxplots-for-education-dataset)

hope this help.

**Comment by SpaceDustPi** [comment]
Thanks, but sample_data.csv is not a part of that. I ended up copy and pasting after printing it out on the Datacamp IDE.

**Comment by goodboychan** [comment]
I see.
Is there anything you need?
